/**
 * Builds drizzle/seed.sql from the versioned seed files in /data.
 *
 * Seed content is IMMUTABLE once used: never edit an existing versioned file,
 * add a new version (e.g. gbp-core-v2.json) instead. Inserts use
 * INSERT OR IGNORE with deterministic IDs, so re-running is safe and never
 * overwrites rows already referenced by audits or tasks.
 *
 * Usage:
 *   npx tsx scripts/build-seed-sql.ts
 *   npx wrangler d1 execute gmb-optimisation --local --file=./drizzle/seed.sql
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const now = Math.floor(Date.now() / 1000);

function sql(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  return `'${String(v).replace(/'/g, "''")}'`;
}

const lines: string[] = [
  "-- Generated by scripts/build-seed-sql.ts — do not edit by hand.",
];

// --- Audit templates -------------------------------------------------------
type AuditFile = {
  key: string;
  version: number;
  name: string;
  description?: string;
  items: Record<string, unknown>[];
};

const auditDir = join(root, "data", "audits");
for (const file of readdirSync(auditDir).filter((f) => f.endsWith(".json"))) {
  const doc = JSON.parse(
    readFileSync(join(auditDir, file), "utf8"),
  ) as AuditFile;
  const templateId = `at_${doc.key}_v${doc.version}`;
  lines.push(
    `INSERT OR IGNORE INTO audit_templates (id, key, version, name, description, source_file, created_at) VALUES (` +
      [
        sql(templateId),
        sql(doc.key),
        sql(doc.version),
        sql(doc.name),
        sql(doc.description ?? null),
        sql(`data/audits/${file}`),
        sql(now),
      ].join(", ") +
      `);`,
  );
  doc.items.forEach((item, i) => {
    const id = `${templateId}:${item.stable_key}`;
    lines.push(
      `INSERT OR IGNORE INTO audit_items (id, template_id, stable_key, section, sort_order, check_title, check_question, why_it_matters, review_guidance, evidence_required, default_severity, risk_level, recommended_action, task_template_key) VALUES (` +
        [
          sql(id),
          sql(templateId),
          sql(item.stable_key),
          sql(item.section),
          sql(i + 1),
          sql(item.check_title),
          sql(item.check_question),
          sql(item.why_it_matters ?? null),
          sql(item.review_guidance ?? null),
          sql(Boolean(item.evidence_required)),
          sql(item.default_severity ?? "standard"),
          sql(item.risk_level ?? "low"),
          sql(item.recommended_action ?? null),
          sql(item.task_template_key ?? null),
        ].join(", ") +
        `);`,
    );
  });
}

// --- Task templates --------------------------------------------------------
type TaskFile = {
  version: number;
  templates: Record<string, unknown>[];
};

const taskDir = join(root, "data", "tasks");
for (const file of readdirSync(taskDir).filter((f) => f.endsWith(".json"))) {
  const doc = JSON.parse(readFileSync(join(taskDir, file), "utf8")) as TaskFile;
  for (const t of doc.templates) {
    const id = `tt_${t.key}_v${doc.version}`;
    lines.push(
      `INSERT OR IGNORE INTO task_templates (id, key, version, title, task_type, instructions, default_priority, default_risk, definition_of_done, approval_required, default_due_days, recurrence_days, prepares_content, is_active) VALUES (` +
        [
          sql(id),
          sql(t.key),
          sql(doc.version),
          sql(t.title),
          sql(t.task_type),
          sql(t.instructions ?? null),
          sql(t.default_priority ?? "p2"),
          sql(t.default_risk ?? "low"),
          sql(t.definition_of_done ?? null),
          sql(Boolean(t.approval_required)),
          sql(t.default_due_days ?? null),
          sql(t.recurrence_days ?? null),
          sql(Boolean(t.prepares_content)),
          sql(1),
        ].join(", ") +
        `);`,
    );
  }
}

mkdirSync(join(root, ".seed"), { recursive: true });
writeFileSync(join(root, ".seed", "seed.sql"), lines.join("\n") + "\n");
console.log(`Wrote .seed/seed.sql (${lines.length - 1} statements)`);
